name: D&D 5e
pool:
  - 1d20<main>
  - 1d20
pipeline:
  - total_adv = max rolled
  - maindice = filter rolled where tag = main
  - total_main = sum maindice
  - total_dis = min rolled
outcomes:
  - Hit with adv when total_adv >= 10
  - Hit normal when total_main >= 10
  - Hit with Dis when total_dis >= 10
